import type { ProfileComparisonRecord } from "@/lib/profile-comparison/types";

export const MOCK_COMPARISON_PREVIEW: ProfileComparisonRecord = {
  id: "00000000-0000-4000-8000-000000000001",
  comparisonType: "person_vs_person",
  status: "completed",
  initiatorProfileId: null,
  leftSide: {
    entityType: "profile",
    entityIds: [],
    label: "Persoon A",
  },
  rightSide: {
    entityType: "profile",
    entityIds: [],
    label: "Persoon B",
  },
  similarityScore: 72,
  result: {
    similarityScore: 72,
    sharedTopValues: [
      {
        id: "integriteit",
        nameAf: "Integriteit",
        nameEn: "Integrity",
        leftRank: 1,
        rightRank: 2,
      },
      {
        id: "gesin",
        nameAf: "Gesin",
        nameEn: "Family",
        leftRank: 3,
        rightRank: 4,
      },
      {
        id: "vryheid",
        nameAf: "Vryheid",
        nameEn: "Freedom",
        leftRank: 5,
        rightRank: 6,
      },
    ],
    biggestDifferences: [
      {
        id: "prestasie",
        nameAf: "Prestasie",
        nameEn: "Achievement",
        side: "left",
        rank: 2,
        otherRank: 9,
      },
      {
        id: "stabiliteit",
        nameAf: "Stabiliteit",
        nameEn: "Stability",
        side: "right",
        rank: 1,
        otherRank: 8,
      },
    ],
    valueMapOverlay: [
      {
        id: "integriteit",
        nameAf: "Integriteit",
        category: "waarheid-beginsels",
        axisX: -0.12,
        axisY: 0.58,
        presence: "shared",
        leftRank: 1,
        rightRank: 2,
      },
      {
        id: "gesin",
        nameAf: "Gesin",
        category: "mense-verhoudings",
        axisX: -0.72,
        axisY: 0.18,
        presence: "shared",
        leftRank: 3,
        rightRank: 4,
      },
      {
        id: "prestasie",
        nameAf: "Prestasie",
        category: "prestasie-groei",
        axisX: 0.68,
        axisY: -0.58,
        presence: "left_only",
        leftRank: 2,
      },
      {
        id: "stabiliteit",
        nameAf: "Stabiliteit",
        category: "orde-stabiliteit",
        axisX: 0.08,
        axisY: 0.78,
        presence: "right_only",
        rightRank: 1,
      },
    ],
    aiInsights: null,
  },
  metadata: { preview: true },
  createdAt: new Date().toISOString(),
};
