// This file is auto-generated by scripts/generate-value-poster-map.mjs
// Add posters to public/value-posters/{valueId}.png, then run npm run generate:value-posters

export const VALUE_POSTER_IDS = ["aanpasbaarheid", "adventure", "authenticity", "courage", "creativity", "curiosity", "freedom", "friendship", "justice", "love", "ontdekking", "openheid", "religion", "vernuwing"] as const;

export type ValuePosterId = (typeof VALUE_POSTER_IDS)[number];

export function hasValuePoster(valueId: string): valueId is ValuePosterId {
  return (VALUE_POSTER_IDS as readonly string[]).includes(valueId);
}

export function getValuePosterSrc(valueId: string): string | null {
  if (!hasValuePoster(valueId)) {
    return null;
  }

  return `/value-posters/${valueId}.png`;
}
